### PR TITLE
dev: add ordinal compare to udp primitive types

### LINKED ISSUE #206: Add `Ord` and `PartialOrd` to the Udp Protocol primitive types.
Hello @greatest-ape ,

In Torrust, there are occasions where the only limiting factor from directly using the aquatic primitives is the lack of ordinal compare.

Can you please consider adding the `Ord` and `PartialOrd` derives to all the types in https://github.com/greatest-ape/aquatic/blob/master/crates/udp_protocol/src/common.rs ?

This would make our primitive types types more compatible, and allow us to use these types directly in b-tree's.

Kind Regards,
Cameron.

### PR DESCRIPTION
**Pull request by da2ce7**
Adds Ordinal Compare to the Primitive Types in: https://github.com/greatest-ape/aquatic/blob/master/crates/udp_protocol/src/common.rs

closes #206

### CODE REVIEW

**Comment by greatest-ape** [comment]
Thanks!

Could you please move the new trait implementations to the common.rs file, with each one under the corresponding struct?

**Comment by da2ce7** [comment]
@greatest-ape done, all the trait implementations are now in the `common.rs` file.

**Comment by greatest-ape** [comment]
Nice, thanks!

**Comment by da2ce7** [comment]
@greatest-ape  Thank You for merging. It has been a couple of months, can you please create a point release so that we can easily use this update in our project?

**Comment by greatest-ape** [comment]
A new release is currently kind of blocked on the failing CI, which is probably due to some change in GitHub workers no longer allowing io_uring use (?). Unfortunrately, at the moment, I don’t have time to look into it.

**Pull request merged**
